//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSE_transport_manager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HSE_transport_manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while connecting database!.
        /// </summary>
        internal static string Error_while_connecting_database_message {
            get {
                return ResourceManager.GetString("Error_while_connecting_database_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:
        ///  От: {1} {2}
        ///  До: {3} {4}.
        /// </summary>
        internal static string ResponseBuilder_FastestWayResponse_message {
            get {
                return ResourceManager.GetString("ResponseBuilder_FastestWayResponse_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расписание автобусов из {0}:
        ///{1}.
        /// </summary>
        internal static string ResponseBuilder_GetBusResponse_Bus_response_header_message {
            get {
                return ResourceManager.GetString("ResponseBuilder_GetBusResponse_Bus_response_header_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. - {1}.  {2} -- {3}.
        /// </summary>
        internal static string ResponseBuilder_GetBusResponse_Schedule_line_pattern {
            get {
                return ResourceManager.GetString("ResponseBuilder_GetBusResponse_Schedule_line_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} -- {1}
        /// Тип: {2} {3}р..
        /// </summary>
        internal static string ResponseBuilder_GetSuburbanResponse_message {
            get {
                return ResourceManager.GetString("ResponseBuilder_GetSuburbanResponse_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная станция! Повторите попытку..
        /// </summary>
        internal static string ResponseBuilder_GetSuburbanResponse_Unknown_station_message {
            get {
                return ResourceManager.GetString("ResponseBuilder_GetSuburbanResponse_Unknown_station_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка выполнения запроса! Проверьте входные данные..
        /// </summary>
        internal static string ResponseBuilder_Input_data_value_error {
            get {
                return ResourceManager.GetString("ResponseBuilder_Input_data_value_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный ввод! Данные должны быть в формате Место - Место..
        /// </summary>
        internal static string ResponseBuilder_Input_separator_error_message {
            get {
                return ResourceManager.GetString("ResponseBuilder_Input_separator_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внутренняя ошибка сервера..
        /// </summary>
        internal static string ResponseBuilder_Internal_error_message {
            get {
                return ResourceManager.GetString("ResponseBuilder_Internal_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка построения маршрута: метро не работает!
        ///Попробуйте повторить ваш запрос позже..
        /// </summary>
        internal static string ResponseBuilder_No_public_transport_error_message {
            get {
                return ResourceManager.GetString("ResponseBuilder_No_public_transport_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Char similar to -.
        /// </summary>
        internal static char ResponseBuilder_TaxiResponse_Separator {
            get {
                object obj = ResourceManager.GetObject("ResponseBuilder_TaxiResponse_Separator", resourceCulture);
                return ((char)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update: .
        /// </summary>
        internal static string SettingsViewModel_Last_update_message {
            get {
                return ResourceManager.GetString("SettingsViewModel_Last_update_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving file!.
        /// </summary>
        internal static string SettingsViewModel_Reset_Error_saving_file_message {
            get {
                return ResourceManager.GetString("SettingsViewModel_Reset_Error_saving_file_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading data in Database....
        /// </summary>
        internal static string SettingsViewModel_Update_DB_message {
            get {
                return ResourceManager.GetString("SettingsViewModel_Update_DB_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading local train schedule from Yandex Service....
        /// </summary>
        internal static string SettingsViewModel_Update_Get_Schedule_message {
            get {
                return ResourceManager.GetString("SettingsViewModel_Update_Get_Schedule_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting data services!.
        /// </summary>
        internal static string Start_No_connecting_services {
            get {
                return ResourceManager.GetString("Start_No_connecting_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error!.
        /// </summary>
        internal static string Start_Unknown_error_message {
            get {
                return ResourceManager.GetString("Start_Unknown_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot is inactive.
        /// </summary>
        internal static string StatusViewModel__botStatus_Bot_is_inactive_message {
            get {
                return ResourceManager.GetString("StatusViewModel__botStatus_Bot_is_inactive_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /get_route.
        /// </summary>
        internal static string StatusViewModel_BotWork__check_message {
            get {
                return ResourceManager.GetString("StatusViewModel_BotWork__check_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot is stopped.
        /// </summary>
        internal static string StatusViewModel_BotWork_Bot_is_stopped_message {
            get {
                return ResourceManager.GetString("StatusViewModel_BotWork_Bot_is_stopped_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для поиска всех возможных путей введите названия начального места и конечной точки в формате: Начальное место - Конечное место.
        /// </summary>
        internal static string StatusViewModel_BotWork_Get_All_routes_response_message {
            get {
                return ResourceManager.GetString("StatusViewModel_BotWork_Get_All_routes_response_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите станцию отправления. Поддерживаются следующие станции:
        ///1. Одинцово
        ///2. Дубки
        ///3. Славянский Бульвар.
        /// </summary>
        internal static string StatusViewModel_BotWork_Get_Bus_response_message {
            get {
                return ResourceManager.GetString("StatusViewModel_BotWork_Get_Bus_response_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для поиска кратчайшего пути введите названия начального места и конечной точки в формате:
        ///Начальное место - Конечное место.
        /// </summary>
        internal static string StatusViewModel_BotWork_Get_route_intro {
            get {
                return ResourceManager.GetString("StatusViewModel_BotWork_Get_route_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расписание электричек из Одинцово. Поддерживаются следующие станции:
        ///1. Кунцево
        ///2. Фили
        ///3. Беговая
        ///4. Белорусский вокзал.
        /// </summary>
        internal static string StatusViewModel_BotWork_Get_suburban_message {
            get {
                return ResourceManager.GetString("StatusViewModel_BotWork_Get_suburban_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я - телеграм бот для поиска всех возможных путей в университет для студентов НИУ ВШЭ!
        ///Умею следующие команды:
        ///  /places - Список поддерживаемых мест
        ///  /get_route - Поиск самого быстрого пути в университет
        ///  /get_all_routes - все возможные пути в университет
        ///  /taxi_route - Расчет времени и стоимость дороги в университет на такси
        ///  /get_suburban - Расписание электричек между станциями
        ///  /get_bus - Расписание до/из Дубков.
        /// </summary>
        internal static string StatusViewModel_BotWork_Intro_message {
            get {
                return ResourceManager.GetString("StatusViewModel_BotWork_Intro_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет!.
        /// </summary>
        internal static string StatusViewModel_BotWork_Introduce_message {
            get {
                return ResourceManager.GetString("StatusViewModel_BotWork_Introduce_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cписок поддерживаемых мест:
        /// {0}.
        /// </summary>
        internal static string StatusViewModel_BotWork_Places_response_message {
            get {
                return ResourceManager.GetString("StatusViewModel_BotWork_Places_response_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Даша Бог БД.
        /// </summary>
        internal static string StatusViewModel_BotWork_That_message {
            get {
                return ResourceManager.GetString("StatusViewModel_BotWork_That_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поездка на такси:
        ///{0} - {1}
        ///Время в пути: {2} минут(ы) 
        ///Стоимость поездки: {3} руб..
        /// </summary>
        internal static string StatusViewModel_BotWork_Uber_response_message {
            get {
                return ResourceManager.GetString("StatusViewModel_BotWork_Uber_response_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная команда!
        ///Введите /start для получения списка возможных комманд..
        /// </summary>
        internal static string StatusViewModel_BotWork_Unknown_message {
            get {
                return ResourceManager.GetString("StatusViewModel_BotWork_Unknown_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неподдерживаемый тип сообщения!
        ///Введите /start для получения списка возможных комманд..
        /// </summary>
        internal static string StatusViewModel_BotWork_Unsupported_message {
            get {
                return ResourceManager.GetString("StatusViewModel_BotWork_Unsupported_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string StatusViewModel_CheckSettings_OK_status_message {
            get {
                return ResourceManager.GetString("StatusViewModel_CheckSettings_OK_status_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot is active.
        /// </summary>
        internal static string StatusViewModel_Start_Bot_is_active_message {
            get {
                return ResourceManager.GetString("StatusViewModel_Start_Bot_is_active_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading dll libraries!.
        /// </summary>
        internal static string StatusViewModel_Start_DLL_load_error_message {
            get {
                return ResourceManager.GetString("StatusViewModel_Start_DLL_load_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading services!.
        /// </summary>
        internal static string StatusViewModel_Start_Load_error_message {
            get {
                return ResourceManager.GetString("StatusViewModel_Start_Load_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot is offline.
        /// </summary>
        internal static string StatusViewModel_Stop_Bot_is_offline_message {
            get {
                return ResourceManager.GetString("StatusViewModel_Stop_Bot_is_offline_message", resourceCulture);
            }
        }
    }
}
